### ISSUE TITLE
.... addNumerical... is not applicable for the arguments

### ISSUE THREAD

**Issue by lmfwmi** [MenoData/Time4J#346] opened 2015-09-02 08:43 UTC
After adding Time4J to my project, I got an error in pkg (net.time4j.format.expert) class (PatternType) line (1531 and 1534), error message in line 1531:

Bound mismatch: The generic method addNumerical(ChronoElement<V>, int, int) of type ChronoFormatter<T>.Builder<T> is not applicable for the arguments (ChronoElement<Enum<Enum<V>>>, int, int). The inferred type Enum<Enum<V>> is not a valid substitute for the bounded parameter <V extends Enum<V>>

line 1534:

Bound mismatch: The generic method addFixedNumerical(ChronoElement<V>, int) of type ChronoFormatter<T>.Builder<T> is not applicable for the arguments (ChronoElement<Enum<Enum<V>>>, int). The inferred type Enum<Enum<V>> is not a valid substitute for the bounded parameter <V extends Enum<V>>

**Comment by MenoData** [comment] 2015-09-02 21:53
First I was not able to reproduce your problem - neither in a Java-6-environment nor on Android Studio emulator. Then I discovered that the Java-8-code in master-branch (v4.4) has a slightly different code handling the generified methods mentioned above. I tested the code of `PatternType`(v3.6) in v4.4 (Java-8-environment) and could produce this compiler error which is very similar to your observation:

[ERROR] C:\work\time4j-master\i18n\src\main\java\net\time4j\format\expert\PatternType.java:[1874,23] error: method addNumerical in class Builder<T> cannot be applied to given types;
[ERROR] required: ChronoElement<V#1>,int,int
[ERROR] found: ChronoElement<V#2>,int,int
[ERROR] reason: inferred type does not conform to upper bound(s)
[ERROR] inferred: V#3
[ERROR] upper bound(s): Enum<V#3>,Enum<V#4>
[ERROR] where V#1,T,V#2,V#3,V#4 are type-variables:
[ERROR] V#1 extends Enum<V#1> declared in method <V#1>addNumerical(ChronoElement<V#1>,int,int)
[ERROR] T extends ChronoEntity<T> declared in class Builder
[ERROR] V#2 extends Enum<V#2>
[ERROR] V#3 extends Enum<V#4>
[ERROR] V#4 extends Enum<V#3>

So it seems you use Java-8 as SDK on Android, right??? Well, I will adjust the v3.x-code so it will hopefully work on all platforms and soon release v3.7 containing the fix.

**Comment by MenoData** [comment] 2015-09-03 01:06
Have just now released Time4A-v3.7-2015f. Please be so kind to give me feedback if this new version solves your problem.

**Comment by MenoData** [comment] 2015-09-13 03:17
Just to note:

The earlier erroraneous version v3.6-2015f offers a workaround using the builder-approach instead of the pattern. The demo example

```java
     ChronoFormatter<HijriCalendar> formatter =
       ChronoFormatter.setUp(HijriCalendar.class, Locale.ENGLISH)
       .addPattern("d. MMMM yy", PatternType.NON_ISO_DATE).build()
       .withCalendarVariant(HijriCalendar.VARIANT_UMALQURA)
       .with(Attributes.PIVOT_YEAR, 1500); // mapped to range 1400-1499
     HijriCalendar hijri = formatter.parse("29. Ramadan 36");
     PlainDate date = hijri.transform(PlainDate.class);
     System.out.println(date); // 2015-07-16
```

is equivalent to:

```java
     ChronoFormatter<HijriCalendar> formatter =
       ChronoFormatter.setUp(HijriCalendar.class, Locale.ENGLISH)
       .addInteger(HijriCalendar.DAY_OF_MONTH, 1, 2)
       .addLiteral(". ")
       .addText(HijriCalendar.MONTH_OF_YEAR)
       .addLiteral(" ")
       .addTwoDigitYear(HijriCalendar.YEAR_OF_ERA)
       .build()
       .withCalendarVariant(HijriCalendar.VARIANT_UMALQURA)
       .with(Attributes.TEXT_WIDTH, TextWidth.WIDE)
       .with(Attributes.PIVOT_YEAR, 1500); // mapped to range 1400-1499
     HijriCalendar hijri = formatter.parse("29. Ramadan 36");
     PlainDate date = hijri.transform(PlainDate.class);
     System.out.println(date); // 2015-07-16
```
Latter one will always work. But I also think that the last version v3.7-2015f is a valid fix.

**Comment by MenoData** [comment] 2015-09-15 03:17
I close this issue for now since I have not got any negative feedback after the last fix. If you still think that the problem continues with the newest version v3.7-2015f then please open a new issue where you describe in detail your environment (for example which IDE, which version of Android SDK etc.) and how to reproduce the problem (complete short code example for Android).

**Closed by MenoData** 2015-09-15 03:17 UTC
Labels: bug, fixed

**Comment by MenoData** [comment] 2015-09-30 17:24
A side note: The coming release v3.9-2015f contains a small change to eliminate any compiler warnings triggered in the class `PatternType`.
