### ISSUE TITLE
Initialization error on startup (Android)

### ISSUE THREAD

**Issue by aazhevsky** [MenoData/Time4J#897] opened 2020-04-16 07:01 UTC
Hi!
Getting this crash rarely while calling `ApplicationStarter.initialize(this, true);` on `App.onCreate`:
```
java.lang.NullPointerException: 
  at net.time4j.format.Attributes$Builder.build (Attributes.java)
  at net.time4j.format.Attributes$Builder.set (Attributes.java)
  at net.time4j.format.Attributes$Builder.set (Attributes.java)
  at net.time4j.format.Attributes$Builder.set (Attributes.java)
  at net.time4j.format.Attributes$Builder.set (Attributes.java)
  at net.time4j.format.Attributes$Builder.setAll (Attributes.java)
  at net.time4j.format.Attributes$Builder.setInternal (Attributes.java)
  at net.time4j.format.Attributes$Builder.setLanguage (Attributes.java)
  at net.time4j.format.Attributes$Builder.setTimezone (Attributes.java)
  at net.time4j.format.expert.AttributeSet.createDefaults (AttributeSet.java)
  at net.time4j.format.expert.AttributeSet.get (AttributeSet.java)
  at net.time4j.format.expert.AttributeSet.get (AttributeSet.java)
  at net.time4j.format.expert.AttributeSet.getAttributes (AttributeSet.java)
  at net.time4j.format.expert.AttributeSet.isEqual (AttributeSet.java)
  at net.time4j.format.expert.AttributeSet.merge (AttributeSet.java)
  at net.time4j.format.expert.AttributeSet.withAttributes (AttributeSet.java)
  at net.time4j.format.expert.AttributeSet.withLocale (AttributeSet.java)
  at net.time4j.format.expert.AttributeSet.createDefaults (AttributeSet.java)
  at net.time4j.format.expert.AttributeSet.get (AttributeSet.java)
  at net.time4j.format.expert.AttributeSet.get (AttributeSet.java)
  at net.time4j.format.expert.AttributeSet.getAttributes (AttributeSet.java)
  at net.time4j.format.expert.AttributeSet.isEqual (AttributeSet.java)
  at net.time4j.format.expert.AttributeSet.merge (AttributeSet.java)
  at net.time4j.format.expert.AttributeSet.withAttributes (AttributeSet.java)
  at net.time4j.format.expert.AttributeSet.withLocale (AttributeSet.java)
  at net.time4j.format.expert.ChronoFormatter.<init> (ChronoFormatter.java)
  at net.time4j.format.expert.ChronoFormatter.<init> (ChronoFormatter.java)
  at net.time4j.format.expert.ChronoFormatter$Builder.access$100 (ChronoFormatter.java)
  at net.time4j.format.expert.ChronoFormatter$Builder.access$400 (ChronoFormatter.java)
  at net.time4j.format.expert.ChronoFormatter$Builder.access$500 (ChronoFormatter.java)
  at net.time4j.format.expert.ChronoFormatter$Builder.addCustomized (ChronoFormatter.java)
  at net.time4j.format.expert.ChronoFormatter$Builder.addDayPeriodApproximate (ChronoFormatter.java)
  at net.time4j.format.expert.ChronoFormatter$Builder.addFixedInteger (ChronoFormatter.java)
  at net.time4j.format.expert.ChronoFormatter$Builder.addFraction (ChronoFormatter.java)
  at net.time4j.format.expert.ChronoFormatter$Builder.addInteger (ChronoFormatter.java)
  at net.time4j.format.expert.ChronoFormatter$Builder.addInteger (ChronoFormatter.java)
  at net.time4j.format.expert.ChronoFormatter$Builder.addLiteral (ChronoFormatter.java)
  at net.time4j.format.expert.ChronoFormatter$Builder.addLiteral (ChronoFormatter.java)
  at net.time4j.format.expert.ChronoFormatter$Builder.addLiteral (ChronoFormatter.java)
  at net.time4j.format.expert.ChronoFormatter$Builder.addLiteralChars (ChronoFormatter.java)
  at net.time4j.format.expert.ChronoFormatter$Builder.addNumber (ChronoFormatter.java)
  at net.time4j.format.expert.ChronoFormatter$Builder.addNumber (ChronoFormatter.java)
  at net.time4j.format.expert.ChronoFormatter$Builder.addPattern (ChronoFormatter.java)
  at net.time4j.format.expert.ChronoFormatter$Builder.addProcessor (ChronoFormatter.java)
  at net.time4j.format.expert.ChronoFormatter$Builder.addText (ChronoFormatter.java)
  at net.time4j.format.expert.ChronoFormatter$Builder.addText (ChronoFormatter.java)
  at net.time4j.format.expert.ChronoFormatter$Builder.addTimezoneOffset (ChronoFormatter.java)
  at net.time4j.format.expert.ChronoFormatter$Builder.addYear (ChronoFormatter.java)
  at net.time4j.format.expert.ChronoFormatter$Builder.build (ChronoFormatter.java)
  at net.time4j.format.expert.ChronoFormatter$Builder.checkAttribute (ChronoFormatter.java)
  at net.time4j.format.expert.ChronoFormatter$Builder.ensureOnlyOneFractional (ChronoFormatter.java)
  at net.time4j.format.expert.ChronoFormatter$Builder.findDayPeriodElement (ChronoFormatter.java)
  at net.time4j.format.expert.ChronoFormatter$Builder.getLevel (ChronoFormatter.java)
  at net.time4j.format.expert.ChronoFormatter$Builder.skipUnknown (ChronoFormatter.java)
  at net.time4j.format.expert.ChronoFormatter$Builder.startOptionalSection (ChronoFormatter.java)
  at net.time4j.format.expert.ChronoFormatter$Builder.startSection (ChronoFormatter.java)
  at net.time4j.format.expert.ChronoFormatter$Builder.startSection (ChronoFormatter.java)
  at net.time4j.format.expert.ChronoFormatter$Builder.startSection (ChronoFormatter.java)
  at net.time4j.format.expert.ChronoFormatter$Builder.build (ChronoFormatter.java)
  at net.time4j.format.expert.ChronoFormatter.access$1000 (ChronoFormatter.java)
  at net.time4j.format.expert.ChronoFormatter.access$1100 (ChronoFormatter.java)
  at net.time4j.format.expert.ChronoFormatter.access$700 (ChronoFormatter.java)
  at net.time4j.format.expert.ChronoFormatter.addPattern (ChronoFormatter.java)
  at net.time4j.format.expert.ChronoFormatter.checkConsistency (ChronoFormatter.java)
  at net.time4j.format.expert.ChronoFormatter.display (ChronoFormatter.java)
  at net.time4j.format.expert.ChronoFormatter.format (ChronoFormatter.java)
  at net.time4j.format.expert.ChronoFormatter.format0 (ChronoFormatter.java)
  at net.time4j.format.expert.ChronoFormatter.freeze (ChronoFormatter.java)
  at net.time4j.format.expert.ChronoFormatter.getAttributes (ChronoFormatter.java)
  at net.time4j.format.expert.ChronoFormatter.getDescription (ChronoFormatter.java)
  at net.time4j.format.expert.ChronoFormatter.isEqual (ChronoFormatter.java)
  at net.time4j.format.expert.ChronoFormatter.ofMomentStyle (ChronoFormatter.java)
  at net.time4j.format.expert.ChronoFormatter.ofPattern (ChronoFormatter.java)
  at net.time4j.format.expert.ChronoFormatter.parse (ChronoFormatter.java)
  at net.time4j.format.expert.ChronoFormatter.parse (ChronoFormatter.java)
  at net.time4j.format.expert.ChronoFormatter.parse (ChronoFormatter.java)
  at net.time4j.format.expert.ChronoFormatter.parse (ChronoFormatter.java)
  at net.time4j.format.expert.ChronoFormatter.parse (ChronoFormatter.java)
  at net.time4j.format.expert.ChronoFormatter.parseElements (ChronoFormatter.java)
  at net.time4j.format.expert.ChronoFormatter.print (ChronoFormatter.java)
  at net.time4j.format.expert.ChronoFormatter.print (ChronoFormatter.java)
  at net.time4j.format.expert.ChronoFormatter.print (ChronoFormatter.java)
  at net.time4j.format.expert.ChronoFormatter.rfc1123DateTime (ChronoFormatter.java)
  at net.time4j.format.expert.ChronoFormatter.setUp (ChronoFormatter.java)
  at net.time4j.format.expert.ChronoFormatter.setValue (ChronoFormatter.java)
  at net.time4j.format.expert.ChronoFormatter.sub (ChronoFormatter.java)
  at net.time4j.format.expert.ChronoFormatter.with (ChronoFormatter.java)
  at net.time4j.format.expert.ChronoFormatter.with (ChronoFormatter.java)
  at net.time4j.format.expert.ChronoFormatter.with (ChronoFormatter.java)
  at net.time4j.format.expert.ChronoFormatter.with (ChronoFormatter.java)
  at net.time4j.format.expert.ChronoFormatter.withTimezone (ChronoFormatter.java)
  at net.time4j.android.ApplicationStarter$1.run (ApplicationStarter.java)
  at java.lang.Thread.run (Thread.java:761)
```

Currently, the affected android versions are 6.0 and 7.0. The crash is obtained from the Google Play developer console. I will update if the issue spread more widely. The library version is `net.time4j:time4j-android:4.4.4-2019c`

Thanks in advance.

**Comment by MenoData** [comment] 2020-04-16 11:38
Thanks for reporting. But is this really a stack trace? We can only see that the presented lines are in alphabetical order and obviously not in call order so it is actually very hard to do a proper analysis. Well, I can do at least two minor changes in formatter code for sake of more stability but it will be a shot in the blue as long as there is no better stack trace.

Maybe the next version of Time4A should contain/preserve the line numbers in generated stack trace (in the hope to achieve call order of lines) - with the side effect that the library might become somehow bigger in byte size (but maybe that is tolerable).

**Comment by aazhevsky** [comment] 2020-04-16 11:48
Sorry, my bad. Firebase shows a different stack trace:
```
net.time4j.format.Attributes$Builder.build (Attributes.java)
net.time4j.format.expert.AttributeSet.createDefaults (AttributeSet.java)
net.time4j.format.expert.AttributeSet.createDefaults (AttributeSet.java)
net.time4j.format.expert.ChronoFormatter.<init> (ChronoFormatter.java)
net.time4j.format.expert.ChronoFormatter.<init> (ChronoFormatter.java)
net.time4j.format.expert.ChronoFormatter$Builder.access$100 (ChronoFormatter.java)
net.time4j.format.expert.ChronoFormatter$Builder.build (ChronoFormatter.java)
net.time4j.format.expert.ChronoFormatter.access$1000 (ChronoFormatter.java)
net.time4j.android.ApplicationStarter$1.run (ApplicationStarter.java)
java.lang.Thread.run (Thread.java:762)
```
Hope it helps.

**Comment by aazhevsky** [comment] 2020-04-17 11:38
One more crash. This time on Android 5 device
```
Fatal Exception: java.lang.IncompatibleClassChangeError
Couldn't find net.time4j.f1.c.value
libcore.reflect.AnnotationAccess.toAnnotationInstance (AnnotationAccess.java:659)
java.lang.Class.getAnnotation (Class.java:343)
net.time4j.format.expert.PatternType.addQuarterOfYear (PatternType.java)
net.time4j.format.expert.PatternType.cldr24 (PatternType.java)
net.time4j.format.expert.PatternType.addQuarterOfYear (PatternType.java)
net.time4j.format.expert.PatternType.addEnumElementAsInteger (PatternType.java)
net.time4j.format.expert.ChronoFormatter$Builder.access$100 (ChronoFormatter.java)
net.time4j.format.expert.ChronoFormatter.access$1000 (ChronoFormatter.java)
net.time4j.format.expert.ChronoFormatter.access$1000 (ChronoFormatter.java)
net.time4j.format.expert.StyleProcessor.createFormatter (StyleProcessor.java)
net.time4j.format.expert.StyleProcessor.createFormatter (StyleProcessor.java)
net.time4j.format.expert.FormatStep.getLevel (FormatStep.java)
net.time4j.format.expert.ChronoFormatter.access$1000 (ChronoFormatter.java)
net.time4j.format.expert.ChronoFormatter.<init> (ChronoFormatter.java)
net.time4j.format.expert.ChronoFormatter.<init> (ChronoFormatter.java)
net.time4j.format.expert.ChronoFormatter$Builder.access$100 (ChronoFormatter.java)
net.time4j.format.expert.ChronoFormatter$Builder.build (ChronoFormatter.java)
net.time4j.format.expert.ChronoFormatter.access$1000 (ChronoFormatter.java)
net.time4j.android.ApplicationStarter$1.run (ApplicationStarter.java)
```

**Comment by MenoData** [comment] 2020-04-17 15:08
About the last crash report: This is something completely different and something which is not caused by Time4A. Instead, I have found a [StackOverflow-discussion](https://stackoverflow.com/questions/47155989/resolve-java-lang-incompatibleclasschangeerror-android-support-v4-content-conte) which seems to address that problem. It sounds as if there is a version conflict between Google Play Services and the concrete SDK on your device.

**Comment by MenoData** [comment] 2020-04-17 15:12
But returning to your first crash report, I have prepared some few changes which I would publish as new release v4.4.5-2019c (probably on Sunday). The resulting APK should also contain extra debug informations for source AND line numbers so I hope the resulting stack traces will be much better in case you should still observe any crash with the new bugfix release.

**Comment by aazhevsky** [comment] 2020-04-17 15:14
Thanks a lot! And have a nice weekend!

**Comment by MenoData** [comment] 2020-04-17 15:20
Another thing which might help in analysis what is going on: 

Can you please show the first lines in your app which use Time4A-code?

**Comment by aazhevsky** [comment] 2020-04-17 15:25
Sure. Here it is:
```
    @Override
    public void onCreate() {
        super.onCreate();
        InAppPurchase.init(this); // initialization of google play billing library
        registerActivityLifecycleCallbacks(new LifecycleCallbacks()); //
        Analytics.init(this); // firebase/facebook analytics initialization
        Experiments.init(this); // firebase remote config initialization
        ApplicationStarter.initialize(this, true); // your code call
        ...

```

**Comment by MenoData** [comment] 2020-04-17 15:36
Oh this is a small misunderstanding. I did not want to see `ApplicationStarter.initialize(...)` but other Time4A-code  being executed in your app (the first lines) in order to analyse how it might interfere with the initialization code. IMHO, you should also test if the line calling `ApplicationStarter` is the very first one (this way giving more time to initialization) or test if you call it without extra thread (second parameter `false`). If then your problem has gone it would indicate an interference problem in two concurrent threads entering static initializers.

**Comment by aazhevsky** [comment] 2020-04-17 15:54
No, another of your code is not supposed to be called yet according to the app logic and other threads state in the reports. But I have a fresh stack trace for you. Now it is from android 8/9 devices and it does contain line numbers:
```
net.time4j.format.Attributes$Builder.a (Attributes.java:172)
net.time4j.format.expert.AttributeSet.a (AttributeSet.java:145)
net.time4j.format.expert.AttributeSet.a (AttributeSet.java:45)
net.time4j.format.expert.ChronoFormatter.<init> (ChronoFormatter.java:26)
net.time4j.format.expert.ChronoFormatter.<init> (ChronoFormatter.java)
net.time4j.format.expert.ChronoFormatter$Builder.a (ChronoFormatter.java:142)
net.time4j.format.expert.ChronoFormatter$Builder.build (ChronoFormatter.java:4)
net.time4j.format.expert.ChronoFormatter.a (ChronoFormatter.java:18)
net.time4j.android.ApplicationStarter$1.run (ApplicationStarter.java:76)
```

**Comment by MenoData** [comment] 2020-04-20 01:57
Just now, I have released v4.4.5-2019c of Time4A. It includes additional debug infos (line numbers) so the size of aar-file has increased from 1.88 MByte to 2.05 MByte. If possible please give me some feedback. The main code change has happened within the class `Attributes` which now uses a cleaner initialization.

**Comment by aazhevsky** [comment] 2020-04-20 08:59
Thank you! I will include the new version into my next release APK. Did you also perform any stability changes?

**Comment by MenoData** [comment] 2020-04-20 09:48
> Did you also perform any stability changes?

Yes, see the changes in the class `net.time4j.format.Attributes`.

**Comment by aazhevsky** [comment] 2020-04-24 07:15
Hi there! Got a fresh crash while using 4.4.5-2019c:
```
Caused by java.lang.NullPointerException
Missing attribute value.
net.time4j.format.Attributes$Builder.set (Attributes.java:1077)
net.time4j.format.expert.AttributeSet.withLocale (AttributeSet.java:399)
net.time4j.format.expert.AttributeSet.createDefaults (AttributeSet.java:302)
net.time4j.format.expert.ChronoFormatter.<init> (ChronoFormatter.java:247)
net.time4j.format.expert.ChronoFormatter.<init> (ChronoFormatter.java:172)
net.time4j.format.expert.ChronoFormatter$Builder.build (ChronoFormatter.java:6655)
net.time4j.format.expert.ChronoFormatter$Builder.build (ChronoFormatter.java:6600)
net.time4j.format.expert.ChronoFormatter.ofMomentStyle (ChronoFormatter.java:2494)
net.time4j.android.ApplicationStarter$StdPrefetch.run (ApplicationStarter.java:290)
```
Previous crashes weren't detected yet.

**Comment by MenoData** [comment] 2020-04-24 11:09
Thank you very much. This is an important step forward because now I see a real stack  trace. I had not been aware of the fact that the compiler setting to get debug infos without line numbers also destroys the call order.

So what does this stack trace now tell us? There is a problem to load the right number system. Before proceeding further, can you tell me the default local on your system including language and possibly country? (should have asked earlier)

**Comment by aazhevsky** [comment] 2020-04-24 16:28
Unfortunately, I can't tell you the faulty country/language codes because I don't collect them for now. 
Will it be enough for your purposes if I collect the mentioned data like:
```
            Crashlytics.setString("country", Locale.getDefault().getCountry());
            Crashlytics.setString("language", Locale.getDefault().getLanguage());
```
 Any suggestions are welcome.

**Comment by MenoData** [comment] 2020-04-24 22:12
Just now I have released Time4A with the new version v4.5-2020a. It should solve your problem. Nevertheless printing the default locale would be nice to know - for sake of more clarity.

**Comment by MenoData** [comment] 2020-05-15 11:59
Well, 3 weeks over without any news about crash. I think it is solved after the last clear error report and analysis and following number system fix so closing this issue. If you find another problem then please open a new issue.

**Closed by MenoData** 2020-05-15 11:59 UTC
Labels: bug, time4a

**Comment by aazhevsky** [comment] 2020-05-15 12:01
Agreed. Unfortunately, I didn't get new info regarding crashes. When I get I'll notify you.
Thanks again for your efforts.

**Comment by aazhevsky** [comment] 2020-06-06 06:20
Hi! 
Sorry for the delay. Here is updated crash info. Time4A version is 4.6-2020a.

Caused by java.lang.IllegalArgumentException: Unknown timezone: Asia/Aden
       at net.time4j.tz.Timezone.getTZ(Timezone.java:1531)
       at net.time4j.tz.Timezone.getTZ(Timezone.java:1414)
       at net.time4j.tz.Timezone.of(Timezone.java:574)
       at net.time4j.format.expert.ChronoFormatter.withTimezone(ChronoFormatter.java:1543)
       at net.time4j.format.expert.ChronoFormatter.ofMomentStyle(ChronoFormatter.java:2494)
       at net.time4j.android.ApplicationStarter$StdPrefetch.run(ApplicationStarter.java:290)
       at java.lang.Thread.run(Thread.java:761)

Android 7.0
country US
language en

**Comment by MenoData** [comment] 2020-06-11 07:02
Thanks for the report although it is something completely different than in this issue which I still consider as beging resolved.

I had first to install some Windows patches to make ADB runnable again so now I could test your problem with some delay.

**Result of my test:** I cannot reproduce. In my setup, all is fine, even with the tzid "Asia/Aden" (which is a link to "Asia/Riyadh"). The prefetch-thread succeeeds as expected with the simulated tz "Asia/Aden" and can load the data of that zone.

**Comment by aazhevsky** [comment] 2020-06-11 07:15
Hi!

Agreed. As I see by crash reports, the latest version is much more stable in my case than the previous one. Since the latest release of my app, I got only three crashes caused by the library and no one is repeated. I also think that they can be caused by faulty installations.
If you wish I can send you the other two cases, probably you can find them interesting.

Thank you again!

**Comment by MenoData** [comment] 2020-06-11 12:40
Okay, you can always send me the crash reports, and I will have a look.

**Comment by aazhevsky** [comment] 2020-06-13 07:22
Please check this crash report. In occurs on Android 5 devices only.
`Caused by java.lang.NullPointerException: Attempt to invoke interface method 'boolean java.util.Set.contains(java.lang.Object)' on a null object reference
       at net.time4j.engine.TimeAxis$Builder.appendUnit(TimeAxis.java:980)
       at net.time4j.PlainTime.registerUnits(PlainTime.java:1912)
       at net.time4j.PlainTime.<clinit>(PlainTime.java:1022)
       at net.time4j.android.ApplicationStarter.initialize(ApplicationStarter.java:170)
       at net.time4j.android.ApplicationStarter.initialize(ApplicationStarter.java:120)
       at com.catalinagroup.callrecorder.App.onCreate(App.java:85)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1035)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6029)
       at android.app.ActivityThread.access$1700(ActivityThread.java:218)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1795)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:145)
       at android.app.ActivityThread.main(ActivityThread.java:6934)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)`

country
BR
language
pt

**Comment by aazhevsky** [comment] 2020-06-13 07:23
And this one on Android 8 devices:
`Caused by java.lang.AssertionError: No NameTypeIndex match for LONG_STANDARD
       at android.icu.impl.TimeZoneNamesImpl$ZNames.getNameTypeIndex(TimeZoneNamesImpl.java:724)
       at android.icu.impl.TimeZoneNamesImpl$ZNames.getName(TimeZoneNamesImpl.java:790)
       at android.icu.impl.TimeZoneNamesImpl.getTimeZoneDisplayName(TimeZoneNamesImpl.java:183)
       at android.icu.text.TimeZoneNames.getDisplayName(TimeZoneNames.java:261)
       at java.util.TimeZone.getDisplayName(TimeZone.java:405)
       at net.time4j.tz.PlatformTimezone.getDisplayName(PlatformTimezone.java:415)
       at net.time4j.format.expert.TimezoneNameProcessor.print(TimezoneNameProcessor.java:168)
       at net.time4j.format.expert.FormatStep.print(FormatStep.java:153)
       at net.time4j.format.expert.ChronoFormatter.print(ChronoFormatter.java:928)
       at net.time4j.format.expert.StyleProcessor.print(StyleProcessor.java:103)
       at net.time4j.format.expert.FormatStep.print(FormatStep.java:153)
       at net.time4j.format.expert.ChronoFormatter.print(ChronoFormatter.java:928)
       at net.time4j.format.expert.ChronoFormatter.format0(ChronoFormatter.java:2802)
       at net.time4j.format.expert.ChronoFormatter.print(ChronoFormatter.java:652)
       at net.time4j.format.expert.ChronoFormatter.format(ChronoFormatter.java:659)
       at net.time4j.android.ApplicationStarter$StdPrefetch.run(ApplicationStarter.java:295)
       at java.lang.Thread.run(Thread.java:764)`

country
BR
language
pt

**Comment by aazhevsky** [comment] 2020-06-13 07:26
This one appears on Android 5 Samsung devices:
`Caused by java.lang.IncompatibleClassChangeError: Couldn't find net.time4j.f1.c.value
       at libcore.reflect.AnnotationAccess.toAnnotationInstance(AnnotationAccess.java:659)
       at libcore.reflect.AnnotationAccess.toAnnotationInstance(AnnotationAccess.java:641)
       at libcore.reflect.AnnotationAccess.getDeclaredAnnotation(AnnotationAccess.java:170)
       at libcore.reflect.AnnotationAccess.getAnnotation(AnnotationAccess.java:72)
       at java.lang.Class.getAnnotation(Class.java:343)
       at net.time4j.format.expert.PatternType.getCalendarType(PatternType.java:1348)
       at net.time4j.format.expert.PatternType.isISO(PatternType.java:1342)
       at net.time4j.format.expert.PatternType.cldr(PatternType.java:1388)
       at net.time4j.format.expert.PatternType.registerSymbol(PatternType.java:1295)
       at net.time4j.format.expert.ChronoFormatter$Builder.addPattern(ChronoFormatter.java:5069)
       at net.time4j.format.expert.ChronoFormatter.addPattern(ChronoFormatter.java:3253)
       at net.time4j.format.expert.ChronoFormatter.ofPattern(ChronoFormatter.java:2360)
       at net.time4j.format.expert.StyleProcessor.createFormatter(StyleProcessor.java:274)
       at net.time4j.format.expert.StyleProcessor.quickPath(StyleProcessor.java:231)
       at net.time4j.format.expert.FormatStep.quickPath(FormatStep.java:444)
       at net.time4j.format.expert.ChronoFormatter.freeze(ChronoFormatter.java:3669)
       at net.time4j.format.expert.ChronoFormatter.<init>(ChronoFormatter.java:407)
       at net.time4j.format.expert.ChronoFormatter.<init>(ChronoFormatter.java:309)
       at net.time4j.format.expert.ChronoFormatter.with(ChronoFormatter.java:1522)
       at net.time4j.format.expert.ChronoFormatter.withTimezone(ChronoFormatter.java:1543)
       at net.time4j.format.expert.ChronoFormatter.ofMomentStyle(ChronoFormatter.java:2494)
       at net.time4j.android.ApplicationStarter$StdPrefetch.run(ApplicationStarter.java:290)
       at java.lang.Thread.run(Thread.java:818)`
country
AE
language
ar

**Comment by MenoData** [comment] 2020-06-17 16:59
> And this one on Android 8 devices:
> Caused by java.lang.AssertionError: No NameTypeIndex match for LONG_STANDARD at android.icu.impl.TimeZoneNamesImpl$ZNames.getNameTypeIndex(TimeZoneNamesImpl.java:724) at android.icu.impl.TimeZoneNamesImpl$ZNames.getName(TimeZoneNamesImpl.java:790) at android.icu.impl.TimeZoneNamesImpl.getTimeZoneDisplayName(TimeZoneNamesImpl.java:183) at android.icu.text.TimeZoneNames.getDisplayName(TimeZoneNames.java:261) at java.util.TimeZone.getDisplayName(TimeZone.java:405) at net.time4j.tz.PlatformTimezone.getDisplayName(PlatformTimezone.java:415) at net.time4j.format.expert.TimezoneNameProcessor.print(TimezoneNameProcessor.java:168) at net.time4j.format.expert.FormatStep.print(FormatStep.java:153) at net.time4j.format.expert.ChronoFormatter.print(ChronoFormatter.java:928) at net.time4j.format.expert.StyleProcessor.print(StyleProcessor.java:103) at net.time4j.format.expert.FormatStep.print(FormatStep.java:153) at net.time4j.format.expert.ChronoFormatter.print(ChronoFormatter.java:928) at net.time4j.format.expert.ChronoFormatter.format0(ChronoFormatter.java:2802) at net.time4j.format.expert.ChronoFormatter.print(ChronoFormatter.java:652) at net.time4j.format.expert.ChronoFormatter.format(ChronoFormatter.java:659) at net.time4j.android.ApplicationStarter$StdPrefetch.run(ApplicationStarter.java:295) at java.lang.Thread.run(Thread.java:764)
> country
> BR
> language
> pt

This crash is an Android platform issue beyond the scope of Time4A, see also [this similar topic](https://github.com/google/volley/issues/177).

**Comment by MenoData** [comment] 2020-06-17 17:02
> This one appears on Android 5 Samsung devices:
> Caused by java.lang.IncompatibleClassChangeError: Couldn't find net.time4j.f1.c.value at libcore.reflect.AnnotationAccess.toAnnotationInstance(AnnotationAccess.java:659) at libcore.reflect.AnnotationAccess.toAnnotationInstance(AnnotationAccess.java:641) at libcore.reflect.AnnotationAccess.getDeclaredAnnotation(AnnotationAccess.java:170) at libcore.reflect.AnnotationAccess.getAnnotation(AnnotationAccess.java:72) at java.lang.Class.getAnnotation(Class.java:343) at net.time4j.format.expert.PatternType.getCalendarType(PatternType.java:1348) at net.time4j.format.expert.PatternType.isISO(PatternType.java:1342) at net.time4j.format.expert.PatternType.cldr(PatternType.java:1388) at net.time4j.format.expert.PatternType.registerSymbol(PatternType.java:1295) at net.time4j.format.expert.ChronoFormatter$Builder.addPattern(ChronoFormatter.java:5069) at net.time4j.format.expert.ChronoFormatter.addPattern(ChronoFormatter.java:3253) at net.time4j.format.expert.ChronoFormatter.ofPattern(ChronoFormatter.java:2360) at net.time4j.format.expert.StyleProcessor.createFormatter(StyleProcessor.java:274) at net.time4j.format.expert.StyleProcessor.quickPath(StyleProcessor.java:231) at net.time4j.format.expert.FormatStep.quickPath(FormatStep.java:444) at net.time4j.format.expert.ChronoFormatter.freeze(ChronoFormatter.java:3669) at net.time4j.format.expert.ChronoFormatter.<init>(ChronoFormatter.java:407) at net.time4j.format.expert.ChronoFormatter.<init>(ChronoFormatter.java:309) at net.time4j.format.expert.ChronoFormatter.with(ChronoFormatter.java:1522) at net.time4j.format.expert.ChronoFormatter.withTimezone(ChronoFormatter.java:1543) at net.time4j.format.expert.ChronoFormatter.ofMomentStyle(ChronoFormatter.java:2494) at net.time4j.android.ApplicationStarter$StdPrefetch.run(ApplicationStarter.java:290) at java.lang.Thread.run(Thread.java:818)
> country
> AE
> language
> ar

Here, I am thinking about a workaround for Time4A in next version to implement an annotation-independent way to achieve the calendar type so Proguard obfuscation cannot defeat it.

**Comment by MenoData** [comment] 2020-06-17 17:10
> Please check this crash report. It occurs on Android 5 devices only.
> Caused by java.lang.NullPointerException: Attempt to invoke interface method 'boolean java.util.Set.contains(java.lang.Object)' on a null object reference at net.time4j.engine.TimeAxis$Builder.appendUnit(TimeAxis.java:980) at net.time4j.PlainTime.registerUnits(PlainTime.java:1912) at net.time4j.PlainTime.<clinit>(PlainTime.java:1022) at net.time4j.android.ApplicationStarter.initialize(ApplicationStarter.java:170) at net.time4j.android.ApplicationStarter.initialize(ApplicationStarter.java:120) at com.catalinagroup.callrecorder.App.onCreate(App.java:85) at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1035) at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6029) at android.app.ActivityThread.access$1700(ActivityThread.java:218) at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1795) at android.os.Handler.dispatchMessage(Handler.java:102) at android.os.Looper.loop(Looper.java:145) at android.app.ActivityThread.main(ActivityThread.java:6934) at java.lang.reflect.Method.invoke(Method.java) at java.lang.reflect.Method.invoke(Method.java:372) at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
> country
> BR
> language
> pt

I consider this also as an Android platform issue because the same code works on all other platforms (including other Android versions). Effectively, the crash is about using the code `set.contains(null)`. I can try to find a more robust workaround in next Time4A-version.

**Comment by MenoData** [comment] 2021-09-12 13:06
@shawaf92 Which version of Time4A do you use? The last relevant commit has been encapsulated in v4.7-2020a.

**Comment by shawaf92** [comment] 2021-09-12 14:41
Thank you it was old project using old version of time4A , once updated it it's fixed .
